"""add latest updates

Revision ID: 04da6921ce16
Revises: 98b564f17b54
Create Date: 2021-02-20 00:12:55.198378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04da6921ce16'
down_revision = '98b564f17b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_updates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('updates', sa.JSON(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_updates')
    # ### end Alembic commands ###
