"""add uptime to lifts
Revision ID: 269220787fbf
Revises: e154e410ce8f
Create Date: 2021-08-29 10:19:48.193097
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269220787fbf'
down_revision = 'e154e410ce8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifts', sa.Column('uptime', sa.Integer(),
                  server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifts', 'uptime')
    # ### end Alembic commands ###
