"""add lifts

Revision ID: 283191078cf4
Revises: 
Create Date: 2020-03-14 13:57:37.512336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283191078cf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('kind', sa.String(), nullable=False),
                    sa.Column('last_updated', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifts')
    # ### end Alembic commands ###
