"""use subscriber id instead

Revision ID: 514826a76b2b
Revises: 8ed555ccaa92
Create Date: 2020-03-14 22:21:30.773414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514826a76b2b'
down_revision = '8ed555ccaa92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column(
        'subscriber_id', sa.String(), nullable=False))
    op.drop_constraint('subscribers_phone_number_key',
                       'subscribers', type_='unique')
    op.create_unique_constraint(None, 'subscribers', ['subscriber_id'])
    op.drop_column('subscribers', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('phone_number',
                                           sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.create_unique_constraint(
        'subscribers_phone_number_key', 'subscribers', ['phone_number'])
    op.drop_column('subscribers', 'subscriber_id')
    # ### end Alembic commands ###
