"""add season to lifts

Revision ID: 51909df056b7
Revises: f71f10afe911
Create Date: 2020-07-11 13:09:54.517330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51909df056b7'
down_revision = 'f71f10afe911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifts', sa.Column('season', sa.String(), nullable=True))
    op.execute("UPDATE lifts SET season = 'Winter' WHERE season IS NULL")
    op.alter_column('lifts', 'season', nullable=False)
    op.create_index(op.f('ix_lifts_season'), 'lifts', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifts_season'), table_name='lifts')
    op.drop_column('lifts', 'season')
    # ### end Alembic commands ###
