"""update lift indexes

Revision ID: 98b564f17b54
Revises: 42ffbceead8f
Create Date: 2021-02-20 00:11:41.484964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b564f17b54'
down_revision = '42ffbceead8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lifts_season_name', table_name='lifts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lifts_season_name', 'lifts', ['season', 'name'], unique=True)
    # ### end Alembic commands ###
